# The URL the site will be built for
base_url = "https://2e0vgu.github.io"
title = "2E0VGU"

theme = "blow"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
enable_search = true
enable_sidebar = false
enable_adsense = false
enable_multilingue = false
adsense_link = ""

[extra.navbar]
title = "2E0VGU"
items = []

[extra.sidebar]
items = []

[extra.lang]
items = []


[extra.index]
title = "2E0VGU - Amateur Radio"
image = "https://2e0vgu.github.io/images/avatar.jpeg"
image_alt = ""


[extra.default_author]
name = "2E0VGU"
avatar = "https://2e0vgu.github.io/images/avatar.jpeg"
avatar_alt = "The digital version of 2E0VGU"

[extra.social]
codeberg = ""
github = ""
gitlab = ""
twitter = ""
mastodon = ""
linkedin = ""
stackoverflow = "" 
telegram = ""
email = ""
